name: RuboCop

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install RuboCop
        run: gem install rubocop
      - name: Install RuboCop-Rails
        run: gem install rubocop-rails
      - name: Install RuboCop-Rspec
        run: gem install rubocop-rspec
      - name: Run RuboCop
        run: rubocop
